### ISSUE TITLE
The function name for "put" should be "update".

### ISSUE THREAD

**Issue by airpingu** [airpingu/data-store-api#2]
Suggested by Zoltan. The function name for `put` should be `update`. It may fail, if the ID is not present.

**Comment by zolkis** [comment]
The suggestion was to separate the insert and update semantics to different functions, as both were covered by "put()", because they have different error paths. However, in addition to insert and update, there may be "update if exists and insert otherwise", which was covered by "put" and it is also useful in a lot of use cases.  We may keep a function for this, if it is seen useful. With insert and update it is doable by writing more code: attempt an update, and  if it fails, then do an insert.

**Comment by airpingu** [comment]
After some thoughts, what I'd like to do here is:
1. Rename `put` to `update`, where the `update` must eat two parameters: one is the new data object to update and the other is the ID to specify which existing record is going to be updated.
2. Keep the original `add` which is exactly the intention of `insert` we're talking about here. This function must eat a single parameter: the data object to add. The function will then return a Promise resolved with a new ID.

The above changes will perfectly match what we originally defined in:

```
enum DataStoreOperation {
    "add",
    "update",
    "remove",
    "clear",
    "done"
};
```

**Comment by airpingu** [comment]
Resolved this at https://github.com/airpingu/data-store-api/commit/3399567119c9e82cf576867a453b214dcd988d17. Please feel free to reopen this or fire another issue if you don't agree. Thanks!

**Comment by zolkis** [comment]
So now we have insert (add) and put (update). What about "update if exists and insert otherwise"? I think that would be useful, and we could make that a special case of add/insert. 
`Promise<index> insert(any data, bool force)`
where 'data' has a primary key, and where 'force' is false by default meaning a normal insert, but when it is 'true', then it updates an existing record if the primary key of the data already exists and returns the index of the updated data
-

**Comment by airpingu** [comment]
If users know he needs to set `force = true` to update an existing record, he can directly call:

`Promise update (any data, DataStoreKey id);`

Did I misunderstand something?

**Comment by zolkis** [comment]
With the `insert(data, false)` call, a normal insert is done, and if the data already exists, an error is resolved through Promise.
With the `insert(data, true)` call, if the data does not exist, a normal insert is done and returns the index. If the data (identified by primary key/index) exists, updates the data and returns the index (key). (Now IIUR the primary key is described in the specs, and implementations will use that info, so we don't need to specify the primary key name in the API.)

The `update(data, id)` call resolves to error when id does not exist. If the data exists, then an update is done.

These are all different error paths / use cases as far as I can tell. Of course naming could be different, e.g. we could name `insert(data, false)` the normal insert, `insert(data, true)` e.g. as `add(data)` and update stays as it is.

**Comment by airpingu** [comment]
Fire an issue for this at: https://github.com/airpingu/data-store-api/issues/12
